### PR TITLE
ENH/CI/TST: test with Olog docker containers

### PR DESCRIPTION
**Pull request by mrakitin**
This PR is based on #4, but employs a more reproducible Olog service via Docker containers. See `.travis.yml` for the details how to start the containers. In short:
- `docker pull mrakitin/olog-mysql-db:latest`
- `docker pull mrakitin/olog-server:latest`
- run https://github.com/mrakitin/docker-olog-server/blob/nsls2/run-all.sh

I had to trim the tests since there were no predefined records in the database. @shroffk may have an idea how to get it.

### CODE REVIEW

**Comment by mrakitin** [comment]
@danielballan, I agree with your second thought. It's especially convenient since we already have it running on Travis, so the non-*nix developers can use it as a test environment.

**Comment by mrakitin** [comment]
Sounds good, I'll update it soon.

**Comment by tacaswell** [comment]
see https://github.com/mrakitin/pyolog2/pull/1  For some reason github is not letting me push to @mrakitin 's branch from this PR...

**Comment by danielballan** [comment]
I notice that the CI passed on baac564 but failed on 4e3a077, which changed nothing of consequence. I also cannot get it to pass locally. I wonder if the docker images changed?

**Comment by mrakitin** [comment]
I was playing with the images to have a predefined `olog` database. It might have broken something. Working on the fix.

**Comment by danielballan** [comment]
This seems close! Would be nice to push it across the finish line once this deployment is behind us.

**Comment by danielballan** [comment]
Closing, presuming that this work is not relevant since we have pivoted to olog-es.

**Pull request closed without merging**
